spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.data.web.pageable.one-indexed-parameters=true

movieapp.jwt.secret=${MOVIEAPP_JWT_SECRET}
movieapp.jwt.access-token=${MOVIEAPP_JWT_ACCESS_TOKEN:8640000}
movieapp.jwt.refresh-token=${MOVIEAPP_JWT_REFRESH_TOKEN:8640000}

movieapp.frontend-url=${MOVIEAPP_FRONTEND_URL}

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}